language: node_js
node_js:
  - "5"
  - "4"
  - "6"
env:
  global:
    - CXX=g++-4.8 debug='sql,lackey*'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - $CXX --version
  - if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;

script: 'gulp test'
notifications:
  slack: enigma-marketing:yfkKsg1TfkVCvECHeeiLzq7Z
# nop
# nop
